### ISSUE TITLE
BZ2 error

### ISSUE THREAD

**Issue by 0atman** [tr4cefl0w/virustotal3#11]
Getting an odd bz2 error after a successful `pip install virustotal3`:

```python
λ python3
Python 3.7.8 (default, Jul 22 2020, 10:55:01) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import virustotal3
>>> import virustotal3.enterprise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oatman/.pyenv/versions/3.7.8/lib/python3.7/site-packages/virustotal3/enterprise.py", line 6, in <module>
    import bz2
  File "/home/oatman/.pyenv/versions/3.7.8/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by 0atman** [comment]
oh oh oh I hadn't built my python with bz2 support, of course! Sorry!
